[Hotfix/#57] 식물등록 결과창에서 다음 화면으로 안넘어가는 버그 수정
TeamCherish/Cherish-iOS pull request #58
Opened 2022-04-05 14:36 UTC by snowedev

### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
```

## 🌈 PR 요약
저번 PR에서 식물등록 flow를 present, dismiss형식으로 바꾸면서 미처 못바꿨던 부분들이 존재했나봐여 그 부분 수정했어요

근데 회원가입 후 최초 등록시에는 좀 달랐던게
식물 등록이 완료되면 PlantResult에서 
```swift
isCherishDataChanged.shared.status = true
```
요 코드로 인해 메인화면(DetailContentVC)은 아직 식물 데이터를 받아오기 전인데 컬렉션뷰의 첫번째 인덱스를 선택시켜주는 `setCherishPeopleCVSelectedItem` 메서드가 viewWillAppear()에서 호출되고 있는 이슈가 있어서 앱이 크래쉬가 나고 있었어용 

어차피 `cherishPeopleData`의 프로퍼티 옵저버 부분에 그 메서드가 구현이 되어있길래 viewWillAppear()에서는 제거해뒀는데 @Juhee-Hwang 확인 한번만 부탁드립미당

#### Linked Issue
close #57

2022-04-06 06:59 UTC, seohyun-106 approved these changes
빠른 수정 감사드립니다 ..

2022-04-06 14:57 UTC, hwangJi-dev reviewed
이부분 갱신안되는 문제때문에 해놨던것같은데 한번 테스트해보고 다시 코멘트달게요!

2022-04-06 17:04 UTC, hwangJi-dev requested changes

2022-04-06 17:04 UTC, hwangJi-dev commented on Cherish-iOS/Cherish-iOS/Screens/CherishMain/Controllers/DetailContentVC.swift
> -            setCherishPeopleCVSelectedItem()
식물 추가 후에 메인뷰로 재진입시 위 함수가 없으면 눌러진 셀과 보여지는 식물이 다른 버그가 또 생겨서
이 호출부분 다시 살려주시구,

setCherishPeopleCVSelectedItem 함수 내에서 코드를 일단 이렇게 변경 부탁드립니다!
```
    if cherishPeopleData.count > 1 {
            cherishPeopleCV.selectItem(at: IndexPath(item: 1, section: 0), animated: false, scrollPosition: .top)
        }
```

2022-04-10 05:20 UTC, hwangJi-dev approved these changes
확인이요!!!!

2022-04-21 13:20 UTC, merged